import {ref} from "vue";
const fields = {
    cardType: ref(''),
    cardPitch: ref(''),
    cardName: ref(''),
    cardCost: ref(''),
    cardText: ref(''),
    cardPower: ref(''),
    cardHeroIntellect: ref(''),
    cardTalent: ref(''),
    cardTalentCustom: ref(''),
    cardClass: ref(''),
    cardClassCustom: ref(''),
    cardSecondaryClass: ref(''),
    cardSecondaryClassCustom: ref(''),
    cardActionSubtype: ref(''),
    cardActionSubtypeCustom: ref(''),
    cardDefenseReactionSubtype: ref(''),
    cardDefenseReactionSubtypeCustom: ref(''),
    cardEquipmentSubtype: ref(''),
    cardEquipmentSubtypeCustom: ref(''),
    cardInstantSubtype: ref(''),
    cardInstantSubtypeCustom: ref(''),
    cardResourceSubtype: ref(''),
    cardResourceSubtypeCustom: ref(''),
    cardMacroGroup: ref(''),
    cardHeroSubtype: ref(''),
    cardWeaponSubtype: ref(''),
    cardWeaponSubtypeCustom: ref(''),
    cardWeapon: ref(''),
    cardRarity: ref(''),
    cardTokenSubtype: ref(''),
    cardDefense: ref(''),
    cardLife: ref(''),
    cardUploadedArtwork: ref(''),
};

export function useFields() {
    return fields;
}