const cardSettings = {
    dented: {
        default: {
            cardBackground: {
                x: 0,
                y: 0,
                name: 'background',
                id: 'img-background',
                draggable: false,
            },
            cardText: {
                x: 55,
                y: 408,
                draggable: false,
                name: 'card-text-image',
            },
            cardName: {
                x: 88,
                y: 42,
                width: 273.5,
                height: 31,
                fontFamily: 'amanda_std_regular',
                fontSize: 25,
                verticalAlign: "middle",
                align: "center",
                fill: "black",
            },
            cardResource: {
                x: 372.1,
                y: 35,
                width: 48,
                height: 44,
                fontFamily: 'palatino_lt_stdlight',
                fontSize: 19,
                verticalAlign: "middle",
                align: "center",
                stroke: "#C42025",
                strokeWidth: 2,
                fillAfterStrokeEnabled: true,
            },
            cardDefense: {
                x: 352.3,
                y: 572.5,
                width: 24,
                height: 29,
                fontFamily: 'palatino_lt_stdroman',
                fontSize: 20.6,
                verticalAlign: "middle",
                align: "center",
            },
            cardPower: {
                x: 73,
                y: 572.5,
                width: 24,
                height: 29,
                fontFamily: 'palatino_lt_stdroman',
                fontSize: 20.6,
                verticalAlign: "middle",
                align: "center",
            },
            cardTypeText: {
                x: 116.3,
                y: 562.55,
                width: 217.2,
                height: 23,
                fontFamily: 'amanda_std_regular',
                fontSize: 17.6,
                verticalAlign: "middle",
                align: "center",
                fill: "black",
            },
            cardLife: {
                x: 352.1,
                y: 572,
                width: 24,
                height: 29,
                fontFamily: 'palatino_lt_stdlight',
                fontSize: 20.6,
                verticalAlign: "middle",
                align: "center",
            },
            cardRarity: {
                x: 114,
                y: 594,
                width: 12,
                height: 12,
            },
            cardUploadedArtwork: {
                width: 390,
                height: 309,
                x: 30,
                y: 76,
            },
            cardFooterText: {
                x: 128,
                y: 607.9,
                width: 204,
                height: 12,
                fontFamily: 'dialog_cond_semiboldregular, Arial, sans-serif',
                fontSize: 10.43,
                verticalAlign: "top",
                fill: "white",
                align: "left",
            },
            cardArtworkCredits: {
                x: 128,
                y: 595.9,
                width: 204,
                height: 12,
                fontFamily: 'dialog_cond_semiboldregular, Arial, sans-serif',
                fontSize: 10.43,
                verticalAlign: "top",
                fill: "white",
                align: "left",
            },
            copyrightOverlay: {
                x: 305,  // Position where © appears in the dented footer
                y: 595.5,
                width: 10,
                height: 12,
                fontFamily: 'Arial',
                fontSize: 10.43,
                verticalAlign: "top",
                fill: "white",
                align: "center",
            },
            copyrightOverlayBottom: {
                x: 272,  // Position where © appears in the dented footer
                y: 607.5,
                width: 10,
                height: 12,
                fontFamily: 'Arial',
                fontSize: 10.43,
                verticalAlign: "top",
                fill: "white",
                align: "center",
            },
            noResourceImage: {
                x: 371,
                y: 29.9,
                width: 49.8,
                height: 49.8,
            },
            powerImage: {
                x: 30,
                y: 560.2,
                width: 36,
                height: 36,
            },
            defenseImage: {
                x: 383.5,
                y: 561.3,
                width: 36,
                height: 36,
            },
            lifeImage: {
                x: 383.5,
                y: 561.3,
                width: 36,
                height: 36,
            },
        },
        // Specialty cases
        hero: {
            cardName: {
                x: 55.6,
                y: 34.6,
                width: 338.5,
                height: 38,
                fontFamily: 'amanda_std_regular',
                fontSize: 29,
                verticalAlign: "middle",
                align: "center",
                fill: "black",
            },
            cardHeroIntellect: {
                x: 73,
                y: 572.5,
                width: 24,
                height: 29,
                fontFamily: 'palatino_lt_stdroman',
                fontSize: 20.6,
                verticalAlign: "middle",
                align: "center",
            },
            cardUploadedArtwork: {
                width: 390,
                height: 628,
                x: 30,
                y: 76,
            },
        },
        demi_hero: {
            cardName: {
                x: 55.6,
                y: 34.6,
                width: 338.5,
                height: 38,
                fontFamily: 'amanda_std_regular',
                fontSize: 29,
                verticalAlign: "middle",
                align: "center",
                fill: "black",
            },
            cardHeroIntellect: {
                x: 73,
                y: 572.5,
                width: 24,
                height: 29,
                fontFamily: 'palatino_lt_stdroman',
                fontSize: 20.6,
                verticalAlign: "middle",
                align: "center",
            },
            cardUploadedArtwork: {
                width: 390,
                height: 628,
                x: 30,
                y: 76,
            },
        },
        weapon: {
            cardName: {
                x: 70.5,
                y: 33,
                width: 310,
                height: 41,
                fontFamily: 'amanda_std_regular',
                fontSize: 29.1,
                verticalAlign: "middle",
                align: "center",
                fill: "black",
            },
        },
        equipment: {
            cardName: {
                x: 58,
                y: 37.5,
                width: 334,
                height: 31,
                fontFamily: 'amanda_std_regular',
                fontSize: 29.1,
                verticalAlign: "middle",
                align: "center",
                fill: "black",
            },
        },
        token: {
            cardName: {
                x: 58,
                y: 37.5,
                width: 334,
                height: 31,
                fontFamily: 'amanda_std_regular',
                fontSize: 29.1,
                verticalAlign: "middle",
                align: "center",
                fill: "black",
            },
        },
        ally: {
            cardName: {
                x: 58,
                y: 37.5,
                width: 334,
                height: 31,
                fontFamily: 'amanda_std_regular',
                fontSize: 29.1,
                verticalAlign: "middle",
                align: "center",
                fill: "black",
            },
            lifeImage: {
                x: 383.5,
                y: 561.3,
                width: 36,
                height: 36,
            },
        }
    },
    flat: {
        default: {
            cardBackground: {
                x: 0,
                y: 0,
                name: 'background',
                id: 'img-background',
                draggable: false,
            },
            cardText: {
                x: 55,
                y: 408,
                draggable: false,
                name: 'card-text-image',
            },
            cardName: {
                x: 95,
                y: 43,
                width: 261,
                height: 27,
                fontFamily: 'amanda_std_regular',
                fontSize: 25.45,
                verticalAlign: "middle",
                align: "center",
                fill: "black",
            },
            cardResource: {
                x: 373.3,
                y: 34.8,
                width: 48,
                height: 44,
                fontFamily: 'palatino_lt_stdlight',
                fontSize: 19,
                verticalAlign: "middle",
                align: "center",
                stroke: "#C42025",
                strokeWidth: 2,
                fillAfterStrokeEnabled: true,
            },
            cardDefense: {
                x: 362.8,
                y: 562,
                width: 24,
                height: 29,
                fontFamily: 'palatino_lt_stdroman',
                fontSize: 17.2,
                verticalAlign: "middle",
                align: "center",
            },
            cardPower: {
                x: 63.1,
                y: 562,
                width: 24,
                height: 29,
                fontFamily: 'palatino_lt_stdroman',
                fontSize: 17.2,
                verticalAlign: "middle",
                align: "center",
            },
            cardTypeText: {
                x: 110.9,
                y: 562.55,
                width: 228.5,
                height: 23,
                fontFamily: 'amanda_std_regular',
                fontSize: 17.55,
                verticalAlign: "middle",
                align: "center",
                fill: "black",
                scaleX: 1,
                scaleY: 0.96,
            },
            cardLife: {
                x: 362.8,
                y: 562,
                width: 24,
                height: 29,
                fontFamily: 'palatino_lt_stdroman',
                fontSize: 17.2,
                verticalAlign: "middle",
                align: "center",
            },
            cardRarity: {
                x: 27.5,
                y: 596.5,
                width: 12.5,
                height: 12.5,
            },
            cardUploadedArtwork: {
                width: 390,
                height: 309,
                x: 30,
                y: 76,
            },
            cardFooterText: {
                x: 46.4,  // Adjust for left alignment
                y: 598.4,
                width: 314,
                height: 12,
                fontFamily: 'dialog_cond_semiboldregular, "Arial Narrow", "Helvetica Condensed", Arial, sans-serif',
                fontSize: 10,
                verticalAlign: "top",
                fill: "white",
                align: "left",
            },
            cardFooterTextRight: {
                x: 360.5,  // Adjust for right side positioning
                y: 598.4,
                width: 63,
                height: 12,
                fontFamily: 'dialog_cond_semiboldregular, "Arial Narrow", "Helvetica Condensed", Arial, sans-serif',
                fontSize: 10,
                verticalAlign: "top",
                fill: "white",
                align: "right",
            },
            copyrightOverlay: {
                x: 400.7,  // Position where © appears in the dented footer
                y: 599,
                width: 10,
                height: 12,
                fontFamily: 'Arial',
                fontSize: 9,
                verticalAlign: "top",
                fill: "white",
                align: "center",
            },
            noResourceImage: {
                x: 372,  // Adjust these values as needed for flat
                y: 29,
                width: 50,
                height: 50,
            },
            powerImage: {
                x: 28,     // Adjust these values as needed for flat
                y: 553.6,
                width: 30,
                height: 30,
            },
            defenseImage: {
                x: 392,  // Adjust these values as needed for flat
                y: 553.6,
                width: 30,
                height: 30,
            },
            lifeImage: {
                x: 392,  // Adjust these values as needed for flat
                y: 553.6,
                width: 30,
                height: 30,
            },
        },
        hero: {
            cardUploadedArtwork: {
                width: 390,
                height: 628,
                x: 30,
                y: 76,
            },
            cardHeroIntellect: {
                x: 63.1,
                y: 562,
                width: 24,
                height: 29,
                fontFamily: 'palatino_lt_stdroman',
                fontSize: 17.2,
                verticalAlign: "middle",
                align: "center",
            },
            cardName: {
                x: 65.5,
                y: 38.5,
                width: 319,
                height: 27,
                fontFamily: 'amanda_std_regular',
                fontSize: 28.5,
                verticalAlign: "middle",
                align: "center",
                fill: "black",
            },
        },
        demi_hero: {
            cardUploadedArtwork: {
                width: 390,
                height: 628,
                x: 30,
                y: 76,
            },
            cardHeroIntellect: {
                x: 63.1,
                y: 562,
                width: 24,
                height: 29,
                fontFamily: 'palatino_lt_stdroman',
                fontSize: 17.2,
                verticalAlign: "middle",
                align: "center",
            },
            cardName: {
                x: 65.5,
                y: 38.5,
                width: 319,
                height: 27,
                fontFamily: 'amanda_std_regular',
                fontSize: 28.5,
                verticalAlign: "middle",
                align: "center",
                fill: "black",
            },
        },
        weapon: {
            cardName: {
                x: 70.5,
                y: 31.9,
                width: 310,
                height: 41,
                fontFamily: 'amanda_std_regular',
                fontSize: 29.1,
                verticalAlign: "middle",
                align: "center",
                fill: "black",
            },
        },
        equipment: {
            cardName: {
                x: 68.5,
                y: 31.9,
                width: 314,
                height: 41,
                fontFamily: 'amanda_std_regular',
                fontSize: 29.1,
                verticalAlign: "middle",
                align: "center",
                fill: "black",
            },
        },
        token: {
            cardName: {
                x: 68.5,
                y: 31.9,
                width: 314,
                height: 41,
                fontFamily: 'amanda_std_regular',
                fontSize: 29.1,
                verticalAlign: "middle",
                align: "center",
                fill: "black",
            },
        },
        ally: {
            cardName: {
                x: 68.5,
                y: 31.9,
                width: 314,
                height: 41,
                fontFamily: 'amanda_std_regular',
                fontSize: 29.1,
                verticalAlign: "middle",
                align: "center",
                fill: "black",
            },
            lifeImage: {
                x: 392,  // Adjust these values as needed for flat
                y: 553.6,
                width: 30,
                height: 30,
            },
        }
    }
}

export function useCardBackSettings() {
    return cardSettings;
}